import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
@Component({ selector: 'app-client-section', template: '<section class="section-head"><div><app-breadcrumbs [items]="[\'Client\', title]"></app-breadcrumbs><h1>{{title}}</h1><p>{{description}}</p></div><button mat-flat-button color="primary" *ngIf="actionLabel" (click)="notice()"><mat-icon>add</mat-icon>{{actionLabel}}</button></section><mat-card class="section-card"><mat-card-content><div class="section-toolbar"><mat-form-field appearance="outline"><mat-icon matPrefix>search</mat-icon><input matInput placeholder="Search {{title.toLowerCase()}}"></mat-form-field><button mat-stroked-button><mat-icon>tune</mat-icon> Filters</button></div><app-empty-state [icon]="icon" [title]="emptyTitle" [description]="emptyDescription"><button mat-flat-button color="primary" *ngIf="actionLabel" (click)="notice()">{{actionLabel}}</button></app-empty-state></mat-card-content></mat-card>', styles: [':host{display:block}.section-head{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:20px;gap:12px}.section-head h1{font-size:25px;color:#202c3e;margin:9px 0 4px;font-weight:700}.section-head p{font-size:12px;color:#8793a1;margin:0}.section-head button{font-size:10px}.section-card{border:1px solid #e9edf2;border-radius:14px;box-shadow:0 4px 18px #23344d08}.section-card mat-card-content{padding:17px}.section-toolbar{display:flex;gap:10px}.section-toolbar mat-form-field{width:min(100%,360px);font-size:11px}.section-toolbar button{height:40px;font-size:10px}.section-toolbar button mat-icon{font-size:16px}'] })
export class ClientSectionComponent {
  private key = '';
  constructor(route: ActivatedRoute, private router: Router) { this.key = route.snapshot.url[0]?.path || ''; }
  get title(): string { return ({ teachers: 'Teachers', courses: 'Courses', batches: 'Batches', attendance: 'Attendance', fees: 'Fees & payments', admissions: 'Admissions', posts: 'Posts', gallery: 'Gallery', notices: 'Notices', results: 'Results', materials: 'Study materials', website: 'Website', settings: 'Settings' } as Record<string, string>)[this.key] || 'Workspace'; }
  get description(): string { return `Manage ${this.title.toLowerCase()} for Northstar Academy.`; }
  get actionLabel(): string { return ({ teachers: 'Add teacher', courses: 'Add course', batches: 'Create batch', posts: 'Create post', gallery: 'Add photos', notices: 'New notice', materials: 'Upload material' } as Record<string, string>)[this.key] || ''; }
  get icon(): string { return ({ teachers: 'school', courses: 'menu_book', batches: 'groups', attendance: 'event_available', fees: 'payments', admissions: 'person_add', posts: 'article', gallery: 'photo_library', notices: 'campaign', results: 'assignment_turned_in', materials: 'folder_open', website: 'language', settings: 'settings' } as Record<string, string>)[this.key] || 'inbox'; }
  get emptyTitle(): string { return this.key === 'attendance' || this.key === 'fees' || this.key === 'admissions' || this.key === 'results' ? `No ${this.title.toLowerCase()} for this date` : `Your ${this.title.toLowerCase()} will appear here`; }
  get emptyDescription(): string { return 'This section is ready for your mock workspace data. Use the controls above to explore the page layout.'; }
  notice(): void { /* Static UI affordance; no backend action. */ }
}
