export type BusinessKind = 'Coaching Institute' | 'College' | 'Clothing Shop';
export interface MockClient { id: number; name: string; owner: string; type: BusinessKind; email: string; phone: string; address: string; status: 'Active' | 'Inactive'; created: string; color: string; secondary?: string; logo?: string; modules: string[]; }
export interface MockStudent { id: number; studentId: string; name: string; father: string; mother: string; phone: string; email: string; course: string; batch: string; admission: string; feeStatus: 'Paid' | 'Pending' | 'Overdue'; attendance: number; status: 'Active' | 'Inactive'; photo: string; dob: string; gender: string; address: string; city: string; state: string; pincode: string; monthlyFee: number; discount: number; }
export const MOCK_CLIENTS: MockClient[] = [
  { id: 1, name: 'Northstar Academy', owner: 'Jordan Davis', type: 'Coaching Institute', email: 'hello@northstar.edu', phone: '+91 98765 43210', address: 'Indiranagar, Bengaluru', status: 'Active', created: '12 Sep 2026', color: '#138e79', modules: ['Students', 'Courses', 'Fees', 'Website'] },
  { id: 2, name: 'Atelier & Co.', owner: 'Aanya Mehta', type: 'Clothing Shop', email: 'studio@atelier.co', phone: '+91 98450 12345', address: 'Koregaon Park, Pune', status: 'Active', created: '09 Sep 2026', color: '#c5755d', modules: ['Products', 'Orders', 'Customers', 'Website'] },
  { id: 3, name: 'Brightpath Learning', owner: 'Ravi Menon', type: 'Coaching Institute', email: 'team@brightpath.in', phone: '+91 98220 33344', address: 'Adyar, Chennai', status: 'Active', created: '04 Sep 2026', color: '#477cbb', modules: ['Students', 'Courses', 'Fees', 'Website'] },
  { id: 4, name: 'Moss & Thread', owner: 'Ishita Rao', type: 'Clothing Shop', email: 'care@mossandthread.in', phone: '+91 99870 55522', address: 'Bandra West, Mumbai', status: 'Inactive', created: '28 Aug 2026', color: '#a28252', modules: ['Products', 'Orders', 'Customers'] },
  { id: 5, name: 'Summit Tutorials', owner: 'Karan Shah', type: 'Coaching Institute', email: 'info@summitclass.in', phone: '+91 98980 11122', address: 'Navrangpura, Ahmedabad', status: 'Active', created: '21 Aug 2026', color: '#866fba', modules: ['Students', 'Courses', 'Fees', 'Website'] },
  { id: 6, name: 'Sunday Studio', owner: 'Tara Nair', type: 'Clothing Shop', email: 'hello@sundaystudio.shop', phone: '+91 98190 88112', address: 'Fort, Mumbai', status: 'Active', created: '17 Aug 2026', color: '#cb8a51', modules: ['Products', 'Orders', 'Customers', 'Website'] },
  { id: 7, name: 'Greenfield College', owner: 'Ananya Rao', type: 'College', email: 'admissions@greenfield.edu', phone: '+91 98450 22011', address: 'Jayanagar, Bengaluru', status: 'Active', created: '15 Sep 2026', color: '#477cbb', modules: ['Students', 'Teachers', 'Courses', 'Batches', 'Attendance', 'Fees', 'Admissions', 'Results', 'Website'] }
];
export const MOCK_STUDENTS: MockStudent[] = [
  { id: 1, studentId: 'NS-2401', name: 'Aarav Sharma', father: 'Vikram Sharma', mother: 'Neha Sharma', phone: '+91 98765 10001', email: 'aarav.s@email.com', course: 'Class 12 Science', batch: 'Physics · Morning', admission: '12 Jun 2026', feeStatus: 'Paid', attendance: 96, status: 'Active', photo: 'AS', dob: '2009-02-14', gender: 'Male', address: '12 Lake View Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560038', monthlyFee: 4500, discount: 500 },
  { id: 2, studentId: 'NS-2402', name: 'Meera Kapoor', father: 'Amit Kapoor', mother: 'Pooja Kapoor', phone: '+91 98765 10002', email: 'meera.k@email.com', course: 'Class 11 Science', batch: 'Chemistry · Evening', admission: '18 Jun 2026', feeStatus: 'Pending', attendance: 91, status: 'Active', photo: 'MK', dob: '2010-07-09', gender: 'Female', address: '48 Park Street', city: 'Bengaluru', state: 'Karnataka', pincode: '560001', monthlyFee: 4000, discount: 0 },
  { id: 3, studentId: 'NS-2403', name: 'Rohan Verma', father: 'Sanjay Verma', mother: 'Kavita Verma', phone: '+91 98765 10003', email: 'rohan.v@email.com', course: 'Class 12 Science', batch: 'Mathematics · Morning', admission: '22 Jun 2026', feeStatus: 'Overdue', attendance: 78, status: 'Active', photo: 'RV', dob: '2009-11-20', gender: 'Male', address: '8 Richmond Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560025', monthlyFee: 4500, discount: 0 },
  { id: 4, studentId: 'NS-2404', name: 'Diya Iyer', father: 'Prakash Iyer', mother: 'Sangeeta Iyer', phone: '+91 98765 10004', email: 'diya.i@email.com', course: 'Class 10 Foundation', batch: 'Foundation · Afternoon', admission: '02 Jul 2026', feeStatus: 'Paid', attendance: 98, status: 'Active', photo: 'DI', dob: '2011-04-01', gender: 'Female', address: '27 4th Cross', city: 'Bengaluru', state: 'Karnataka', pincode: '560034', monthlyFee: 3200, discount: 200 },
  { id: 5, studentId: 'NS-2405', name: 'Kabir Singh', father: 'Arjun Singh', mother: 'Simran Singh', phone: '+91 98765 10005', email: 'kabir.s@email.com', course: 'Class 12 Commerce', batch: 'Accounts · Evening', admission: '12 Jul 2026', feeStatus: 'Pending', attendance: 86, status: 'Active', photo: 'KS', dob: '2009-08-18', gender: 'Male', address: '65 MG Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560001', monthlyFee: 3500, discount: 0 }
];
