import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { MatDialog } from '@angular/material/dialog';
import { ConfirmationDialogService } from '../core/confirmation-dialog.service';
import { ShopMockDataService, ShopProduct, ShopOrder } from '../core/shop-mock-data.service';
import { RecordDialogComponent, RecordField } from '../client/management/record-dialog.component';
@Component({selector:'app-shop-management',templateUrl:'./shop-management.component.html',styleUrls:['./shop-management.component.scss']})
export class ShopManagementComponent implements OnInit {
  key='products';search='';filter='';view='table';
  readonly productFields:RecordField[]=[{key:'name',label:'Product name',required:true},{key:'category',label:'Category',type:'select',options:['Tops','Bottoms','Dresses','Knitwear','Accessories'],required:true},{key:'sku',label:'SKU',required:true},{key:'size',label:'Size',hint:'e.g. S, M, L or One size'},{key:'color',label:'Color'},{key:'price',label:'Price (₹)',type:'number',required:true},{key:'discount',label:'Discount (%)',type:'number'},{key:'stock',label:'Stock quantity',type:'number',required:true},{key:'image',label:'Product image',type:'file'},{key:'status',label:'Status',type:'select',options:['Active','Inactive'],required:true}];
  constructor(public data:ShopMockDataService,private route:ActivatedRoute,private router:Router,private dialog:MatDialog,private confirm:ConfirmationDialogService){}
  ngOnInit():void{const parts=this.router.url.split('?')[0].split('/').filter(Boolean);this.key=parts[1]||'products';if(this.router.url.endsWith('/add'))setTimeout(()=>this.editProduct(),0);}
  get title():string{return ({products:'Products',categories:'Categories',inventory:'Inventory',orders:'Orders',customers:'Customers',offers:'Offers',reports:'Reports',settings:'Shop settings'} as Record<string,string>)[this.key]||'Shop';}
  get filteredProducts():ShopProduct[]{const q=this.search.toLowerCase().trim();return this.data.products.filter(p=>(!q||`${p.name} ${p.sku} ${p.category} ${p.color}`.toLowerCase().includes(q))&&(!this.filter||p.category===this.filter||p.status===this.filter));}
  get filteredCustomers(){const q=this.search.toLowerCase().trim();return this.data.customers.filter(c=>!q||`${c.name} ${c.phone}`.toLowerCase().includes(q));}
  get getLowStock():number{return this.data.products.filter(p=>p.stock>0&&p.stock<8).length;}
  get totalStock():number{return this.data.products.reduce((sum,p)=>sum+p.stock,0);}
  get outOfStock():number{return this.data.products.filter(p=>p.stock===0).length;}
  get filteredOrders():ShopOrder[]{const q=this.search.toLowerCase().trim();return this.data.orders.filter(o=>(!q||`${o.id} ${o.customer}`.toLowerCase().includes(q))&&(!this.filter||o.status===this.filter));}
  editProduct(product?:ShopProduct):void{const ref=this.dialog.open(RecordDialogComponent,{width:'680px',maxWidth:'calc(100vw - 24px)',data:{title:product?'Edit product':'Add product',submitLabel:product?'Save changes':'Add product',fields:this.productFields,record:product}});ref.afterClosed().subscribe(value=>{if(!value){if(this.router.url.endsWith('/add'))this.router.navigate(['/shop/products']);return;}const row={...value,price:Number(value.price)||0,discount:Number(value.discount)||0,stock:Number(value.stock)||0,stockIn:product?.stockIn||0,stockOut:product?.stockOut||0,image:value.image?.startsWith('blob:')?value.image:product?.image||'assets/images/top-products/01.png'} as Omit<ShopProduct,'id'>;if(product)Object.assign(product,row);else this.data.addProduct(row);if(this.router.url.endsWith('/add'))this.router.navigate(['/shop/products']);});}
  editCategory(category?:any):void{const ref=this.dialog.open(RecordDialogComponent,{width:'520px',maxWidth:'calc(100vw - 24px)',data:{title:category?'Edit category':'Add category',submitLabel:category?'Save category':'Create category',record:category,fields:[{key:'name',label:'Category name',required:true},{key:'description',label:'Description',type:'textarea'},{key:'status',label:'Status',type:'select',options:['Active','Inactive'],required:true}]}});ref.afterClosed().subscribe(value=>{if(value){if(category)Object.assign(category,value);else this.data.categories.unshift({...value,id:Date.now(),products:0,color:'#e9f3ed'});}});}
  addCategory():void{this.editCategory();}
  remove(row:any,kind:string):void{this.confirm.confirm({title:`Delete ${kind}?`,message:`Remove “${row.name||row.title}” from your shop records?`,confirmLabel:`Delete ${kind}`,destructive:true}).subscribe(ok=>{if(ok){if(kind==='product')this.data.products=this.data.products.filter(item=>item!==row);if(kind==='category')this.data.categories=this.data.categories.filter(item=>item!==row);if(kind==='offer')this.data.offers=this.data.offers.filter(item=>item!==row);}});}
  adjustStock(product:ShopProduct,direction:'in'|'out'):void{const ref=this.dialog.open(RecordDialogComponent,{width:'430px',maxWidth:'calc(100vw - 24px)',data:{title:direction==='in'?'Stock in':'Stock out',submitLabel:direction==='in'?'Add to stock':'Remove stock',fields:[{key:'quantity',label:'Quantity',type:'number',required:true},{key:'note',label:'Reason / note',type:'text'}]}});ref.afterClosed().subscribe(value=>{if(value){const qty=Math.max(1,Number(value.quantity)||1);product.stock=Math.max(0,product.stock+(direction==='in'?qty:-qty));if(direction==='in')product.stockIn+=qty;else product.stockOut+=Math.min(qty,product.stock+qty);}});}
  editOffer(row?:any):void{const ref=this.dialog.open(RecordDialogComponent,{width:'520px',maxWidth:'calc(100vw - 24px)',data:{title:row?'Edit offer':'Create offer',submitLabel:row?'Save offer':'Create offer',record:row,fields:[{key:'name',label:'Offer name',required:true},{key:'discount',label:'Discount',required:true},{key:'start',label:'Start date',type:'date',required:true},{key:'end',label:'End date',type:'date',required:true},{key:'status',label:'Status',type:'select',options:['Active','Scheduled','Expired'],required:true}]}});ref.afterClosed().subscribe(value=>{if(value){if(row)Object.assign(row,value);else this.data.offers.unshift({...value,id:Date.now()});}});}
  setOrderStatus(order:ShopOrder,status:ShopOrder['status']):void{order.status=status;}
  toggleProduct(product:ShopProduct):void{product.status=product.status==='Active'?'Inactive':'Active';}
  downloadReport():void{const csv=['Order,Customer,Date,Items,Total,Status',...this.data.orders.map(o=>`${o.id},${o.customer},${o.date},${o.items},${o.total},${o.status}`)].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='atelier-orders.csv';a.click();URL.revokeObjectURL(a.href);}
  viewCustomer(customer:any):void{const history=this.data.orders.filter(order=>order.customer===customer.name).map(order=>order.id+' · '+order.date+' · ₹'+order.total+' · '+order.status).join('\n')||'No demo orders yet';this.dialog.open(RecordDialogComponent,{width:'520px',maxWidth:'calc(100vw - 24px)',data:{title:'Purchase history · '+customer.name,submitLabel:'Done',readonly:true,record:{...customer,history},fields:[{key:'name',label:'Customer'},{key:'phone',label:'Phone'},{key:'orders',label:'Completed orders'},{key:'spent',label:'Lifetime spend (₹)'},{key:'due',label:'Due amount (₹)'},{key:'lastPurchase',label:'Last purchase'},{key:'history',label:'Recent purchases'}]}});}
  editSettings():void{const ref=this.dialog.open(RecordDialogComponent,{width:'580px',maxWidth:'calc(100vw - 24px)',data:{title:'Edit store settings',submitLabel:'Save settings',record:this.data.store,fields:[{key:'name',label:'Store name',required:true},{key:'type',label:'Business type'},{key:'phone',label:'Phone',required:true},{key:'email',label:'Email',type:'email'},{key:'address',label:'Address',type:'textarea'},{key:'currency',label:'Currency'}]}});ref.afterClosed().subscribe(value=>{if(value)Object.assign(this.data.store,value);});}
  categoryProductCount(category:string):number{return this.data.products.filter(p=>p.category===category).length;}
  get orderStatusOptions():string[]{return ['Pending','Confirmed','Packed','Delivered','Cancelled'];}
  orderCount(status:string):number{return this.data.orders.filter(order=>order.status===status).length;}
  initials(name:string):string{return name.split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase();}
}
